// <auto-generated />
using System;
using BiblioJuegos.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BiblioJuegos.DAL.Migrations
{
    [DbContext(typeof(BiblioJuegosContext))]
    [Migration("20190614144520_ModelosActualizados")]
    partial class ModelosActualizados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BiblioJuegos.BOL.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AgregadoEn");

                    b.Property<string>("ImagenURL");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("BiblioJuegos.BOL.Compania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AgregadoEn");

                    b.Property<string>("ImagenURL");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Companias");
                });

            modelBuilder.Entity("BiblioJuegos.BOL.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AgregadoEn");

                    b.Property<string>("ImagenURL");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Plataformas");
                });

            modelBuilder.Entity("BiblioJuegos.BOL.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AgregadoEn");

                    b.Property<string>("Contra");

                    b.Property<string>("ImagenURL");

                    b.Property<string>("NombeUsuario");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("BiblioJuegos.BOL.Videojuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AgregadoEn");

                    b.Property<int?>("CategoriaId");

                    b.Property<int?>("CompaniaId");

                    b.Property<string>("ImagenURL");

                    b.Property<DateTime>("Lanzamiento");

                    b.Property<int?>("PlataformaId");

                    b.Property<string>("Titulo");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CompaniaId");

                    b.HasIndex("PlataformaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Videojuegos");
                });

            modelBuilder.Entity("BiblioJuegos.BOL.Videojuego", b =>
                {
                    b.HasOne("BiblioJuegos.BOL.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("BiblioJuegos.BOL.Compania", "Compania")
                        .WithMany()
                        .HasForeignKey("CompaniaId");

                    b.HasOne("BiblioJuegos.BOL.Plataforma", "Plataforma")
                        .WithMany()
                        .HasForeignKey("PlataformaId");

                    b.HasOne("BiblioJuegos.BOL.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
